package br.ufes.informatica.rationalontology.core.persistence;

import java.util.List;

import javax.ejb.Local;
import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;
import br.ufes.informatica.rationalontology.core.domain.Access;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface AccessDAO extends BaseDAO<Access> {

	List<Access> getRequests(long ids);
	
}