package br.ufes.informatica.rationalontology.core.persistence;

import java.util.List;

import javax.ejb.Local;
import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;
import br.ufes.informatica.rationalontology.core.domain.Access;
import br.ufes.informatica.rationalontology.core.domain.Ontology;
import br.ufes.informatica.rationalontology.core.domain.User;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface AccessDAO extends BaseDAO<Access> {

	public List<Access> getRequests(User user);
	
	public List<Access> getRequestsToGrant(User user);
	
	public Access getCreatorAccess(Ontology ontology);
	
}