package br.ufes.informatica.rationalontology.core.persistence;

import javax.ejb.Local;

import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;
import br.ufes.informatica.rationalontology.core.domain.Access;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface AccessDAO extends BaseDAO<Access> {

	Access findRequests(String email);

	String requestParticipation(String ontoName, String email);

}