package br.ufes.informatica.rationalontology.core.persistence;

import java.util.ArrayList;
import java.util.List;

import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaDelete;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;
import javax.persistence.criteria.Subquery;

import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseJPADAO;
import br.ufes.informatica.rationalontology.core.domain.Access;
import br.ufes.informatica.rationalontology.core.domain.Access_;
import br.ufes.informatica.rationalontology.core.domain.CompetencyQuestion;
import br.ufes.informatica.rationalontology.core.domain.CompetencyQuestion_;
import br.ufes.informatica.rationalontology.core.domain.Ontology;
import br.ufes.informatica.rationalontology.core.domain.Ontology_;
import br.ufes.informatica.rationalontology.core.domain.SubOntology;
import br.ufes.informatica.rationalontology.core.domain.SubOntology_;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class CompetencyQuestionJPADAO extends BaseJPADAO<CompetencyQuestion> implements CompetencyQuestionDAO{
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
    @PersistenceContext
    private EntityManager entityManager;

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	protected EntityManager getEntityManager() {
		return entityManager;
	}

	@Override 	
	public List<CompetencyQuestion> getCompetenceQuestionBySubOntologies(List<SubOntology> list) {
		
		if(list == null || list.size() == 0) {
			return new ArrayList<CompetencyQuestion>();
		}
		
    	CriteriaBuilder cb = entityManager.getCriteriaBuilder();
    	
		CriteriaQuery<CompetencyQuestion> cq = cb.createQuery(CompetencyQuestion.class);		
		Root<CompetencyQuestion> root = cq.from(CompetencyQuestion.class);
		
		cq.where( root.get(CompetencyQuestion_.Source).in(list) ) ;
		
		TypedQuery<CompetencyQuestion> q = entityManager.createQuery(cq);
		return q.getResultList();
	}
	
}