package br.ufes.informatica.rationalontology.core.persistence;

import java.util.List;

import javax.ejb.Local;
import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;
import br.ufes.informatica.rationalontology.core.domain.CompetenceQuestion;
import br.ufes.informatica.rationalontology.core.domain.SubOntology;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface CompetenceQuestionDAO extends BaseDAO<CompetenceQuestion> {

	public List findCQ(SubOntology subOntology);
	
	//public List<CompetenceQuestion> getCompetenceQuestionByIdOntology(long id);
	
	public List<CompetenceQuestion> getCompetenceQuestionBySubOntologies(List<SubOntology> list);
	
}