package br.ufes.informatica.rationalontology.core.persistence;

import java.util.List;

import javax.ejb.Local;
import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;
import br.ufes.informatica.rationalontology.core.domain.CompetencyQuestion;
import br.ufes.informatica.rationalontology.core.domain.Ontology;
import br.ufes.informatica.rationalontology.core.domain.SubOntology;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface CompetencyQuestionDAO extends BaseDAO<CompetencyQuestion> {
	
	public List<CompetencyQuestion> getCompetenceQuestionBySubOntologies(List<SubOntology> list);
	
}