package br.ufes.informatica.rationalontology.core.persistence;

import java.util.List;

import javax.ejb.Local;

import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;
import br.ufes.informatica.rationalontology.core.domain.DataDictionary;
import br.ufes.informatica.rationalontology.core.domain.Ontology;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface DataDictionaryDAO extends BaseDAO<DataDictionary> {

	List findDataDictionary(Ontology ontology);
}