package br.ufes.informatica.rationalontology.core.persistence;

import javax.ejb.Local;
import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;
import br.ufes.informatica.rationalontology.core.domain.DataDictionary;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface DataDictonaryDAO extends BaseDAO<DataDictionary> {
	
}