package br.ufes.informatica.rationalontology.core.persistence;

import java.util.List;

import javax.ejb.Local;
import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;
import br.ufes.informatica.rationalontology.core.domain.Ontology;
import br.ufes.informatica.rationalontology.core.domain.User;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface OntologyDAO extends BaseDAO<Ontology> {

	public List<Ontology> findOntologyByName(String ontoName);
	
	public List<Ontology> findOntologyByNameNotMine(String ontoName, User user);
	
	public Ontology getOntology(String nickname);
	
	public Ontology findOntologyByID(long id);
	
	public List<Ontology> getOntologiesByUser(User user);
	
}