package br.ufes.informatica.rationalontology.core.persistence;

import java.util.List;

import javax.ejb.Local;
import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;
import br.ufes.informatica.rationalontology.core.domain.Ontology;
import br.ufes.informatica.rationalontology.core.domain.User;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface OntologyDAO extends BaseDAO<Ontology> {

	List findOntologiByName(String ontoName);

	List findUserOntologies(User user);

	Ontology getOntology(String nickname);
	
}