package br.ufes.informatica.rationalontology.core.persistence;

import java.util.List;

import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;

import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseJPADAO;
import br.ufes.informatica.rationalontology.core.domain.Ontology;
import br.ufes.informatica.rationalontology.core.domain.Ontology_;
import br.ufes.informatica.rationalontology.core.domain.SubOntology;
import br.ufes.informatica.rationalontology.core.domain.SubOntology_;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class SubOntologyJPADAO extends BaseJPADAO<SubOntology> implements SubOntologyDAO{
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
    @PersistenceContext
    private EntityManager entityManager;

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	protected EntityManager getEntityManager() {
		return entityManager;
	}
    
    
	/** TODO: generated by FrameWeb. Should be documented. */
    @Override
	public List findSubOntoogies(Ontology ontology) {
		// FIXME: auto-generated method stub
		return null;
	}


	@Override
	public List<SubOntology> getSubOntologyByIdOntology(long id) {
		CriteriaBuilder cb = entityManager.getCriteriaBuilder();
		CriteriaQuery<SubOntology> cq = cb.createQuery(SubOntology.class);		
		Root<SubOntology> root = cq.from(SubOntology.class);

		cq.where(	cb.equal(root.get(SubOntology_.Source), id)) ;
		TypedQuery<SubOntology> q = entityManager.createQuery(cq);
		return q.getResultList();
	}
	

}