package br.ufes.informatica.rationalontology.core.domain;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.validation.constraints.NotNull;

import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Access extends PersistentObjectSupport implements Comparable<Access> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@NotNull
	private Short accessType;

	/** TODO: generated by FrameWeb. Should be documented. */

	private Date canceledData;

	/** TODO: generated by FrameWeb. Should be documented. */
	@ManyToOne
	private User Source;

	/** TODO: generated by FrameWeb. Should be documented. */
	@ManyToOne
	private Ontology Target;

	/** Getter for accessType. */
	public Short getAccessType() {
		return accessType;
	}

	/** Setter for accessType. */
	public void setAccessType(Short accessType) {
		this.accessType = accessType;
	}

	/** Getter for canceledData. */
	public Date getCanceledData() {
		return canceledData;
	}

	/** Setter for canceledData. */
	public void setCanceledData(Date canceledData) {
		this.canceledData = canceledData;
	}

	/** Getter for Source. */
	public User getSource() {
		return Source;
	}

	/** Setter for Source. */
	public void setSource(User Source) {
		this.Source = Source;
	}

	/** Getter for Target. */
	public Ontology getTarget() {
		return Target;
	}

	/** Setter for Target. */
	public void setTarget(Ontology Target) {
		this.Target = Target;
	}

	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Access o) {
		// FIXME: auto-generated method stub
		return super.compareTo(o);
	}
}