package br.ufes.informatica.rationalontology.core.domain;

import java.util.*;
import java.math.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class CompetenceQuestion extends PersistentObjectSupport implements Comparable<CompetenceQuestion> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;



	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull @Size(max = 6) 
	private String identificator;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull @Size(max = 500) 
	private String description;




		
		/** TODO: generated by FrameWeb. Should be documented. */
		@ManyToOne
		private SubOntology Source;
		
	




	/** Getter for identificator. */
	public String getIdentificator() {
		return identificator;
	}
	
	/** Setter for identificator. */
	public void setIdentificator(String identificator) {
		this.identificator = identificator;
	}

	/** Getter for description. */
	public String getDescription() {
		return description;
	}
	
	/** Setter for description. */
	public void setDescription(String description) {
		this.description = description;
	}




		
		/** Getter for Source. */
		public SubOntology getSource() {
			return Source;
		}
		
		/** Setter for Source. */
		public void setSource(SubOntology Source) {
			this.Source = Source;
		}
		
	





	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(CompetenceQuestion o) {
		// FIXME: auto-generated method stub		
		return super.compareTo(o);
	}
}