package br.ufes.informatica.rationalontology.core.application;

import java.io.Serializable;
import java.util.List;

import javax.ejb.Local;

import br.ufes.informatica.rationalontology.core.domain.CompetencyQuestion;
import br.ufes.informatica.rationalontology.core.domain.SubOntology;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface CompetencyQuestionApp extends Serializable {
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public void saveCQ(CompetencyQuestion competencyQuestion);
	
	public List<CompetencyQuestion> getCompetenceQuestionBySubOntology(SubOntology subOntology);
	
	public void deleteCQ(CompetencyQuestion cq);
	
	public void checkAuthorization();
	
}