package br.ufes.informatica.rationalontology.core.application;

import java.io.Serializable;
import javax.ejb.Local;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface CompetenceQuestionApp extends Serializable {
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public void saveCQ();
	
}