package br.ufes.informatica.rationalontology.core.application;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.security.RolesAllowed;
import javax.ejb.EJB;
import javax.ejb.Stateless;

import br.ufes.informatica.rationalontology.core.domain.CompetencyQuestion;
import br.ufes.informatica.rationalontology.core.domain.SubOntology;
import br.ufes.informatica.rationalontology.core.persistence.CompetencyQuestionDAO;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
@RolesAllowed("SysAdmin")
public class CompetencyQuestionAppBean implements CompetencyQuestionApp {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private CompetencyQuestionDAO competencyQuestionDAO;

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public void saveCQ(CompetencyQuestion competencyQuestion) {
		competencyQuestionDAO.save(competencyQuestion);
	}

	@Override
	public List<CompetencyQuestion> getCompetenceQuestionBySubOntology(SubOntology subOntology) {
		List <SubOntology> list = new ArrayList<SubOntology>();
		list.add(subOntology);
		return competencyQuestionDAO.getCompetenceQuestionBySubOntologies(list);
	}

	@Override
	public void deleteCQ(CompetencyQuestion cq) {
		competencyQuestionDAO.delete(cq);
	}

	@Override
	public void checkAuthorization() {
		System.out.println("checkAuthorization");
	}

}