package br.ufes.informatica.rationalontology.core.application;

import java.io.Serializable;
import java.util.List;

import javax.ejb.Local;
import br.ufes.informatica.rationalontology.core.domain.DataDictionary;
import br.ufes.informatica.rationalontology.core.domain.Ontology;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface DataDictionaryApp  extends Serializable{
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public void saveDictionary(DataDictionary dic);
	
	public List<DataDictionary> getDictionaryByOntology(Ontology ontology);
	
	public void deleteTerm (DataDictionary term);
	
	public void checkAuthorization();
	
}