package br.ufes.informatica.rationalontology.core.application;

import java.util.List;

import javax.annotation.security.RolesAllowed;
import javax.ejb.EJB;
import javax.ejb.Stateless;
import br.ufes.informatica.rationalontology.core.domain.DataDictionary;
import br.ufes.informatica.rationalontology.core.domain.Ontology;
import br.ufes.informatica.rationalontology.core.persistence.DataDictionaryDAO;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
@RolesAllowed("SysAdmin")
public class DataDictionaryAppBean implements DataDictionaryApp {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private DataDictionaryDAO dataDictonaryDAO;

	@Override
	public void saveDictionary(DataDictionary dic) {
		dataDictonaryDAO.save(dic);
	}

	@Override
	public List<DataDictionary> getDictionaryByOntology(Ontology ontology) {
		return dataDictonaryDAO.getDataDictionary(ontology);
	}

	@Override
	public void deleteTerm(DataDictionary term) {
		dataDictonaryDAO.delete(term);
	}

	@Override
	public void checkAuthorization() {
		System.out.println("checkAuthorization");
	}


}