package br.ufes.informatica.rationalontology.core.application;

import javax.ejb.EJB;
import javax.ejb.Stateless;

import br.ufes.informatica.rationalontology.core.domain.DataDictionary;
import br.ufes.informatica.rationalontology.core.persistence.DataDictionaryDAO;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class DictionaryControllerBean implements DictionaryController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private DataDictionaryDAO dataDictonaryDAO;

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public String saveDictionary(DataDictionary dic) {
		// FIXME: auto-generated method stub
		return null;
	}

}