package br.ufes.informatica.rationalontology.core.application;

import java.io.Serializable;

import javax.ejb.Local;

import br.ufes.informatica.rationalontology.core.domain.DataDictionary;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface DictionaryController extends Serializable {

	/** TODO: generated by FrameWeb. Should be documented. */
	public String saveDictionary(DataDictionary dic);

}