package br.ufes.informatica.rationalontology.core.application;

import java.io.Serializable;
import java.util.List;

import javax.ejb.Local;

import br.ufes.informatica.rationalontology.core.domain.Access;
import br.ufes.informatica.rationalontology.core.exception.SaveException;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface GrantParticipationApp extends Serializable {
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public List<Access> getRequests(long id);
	
	/** TODO: generated by FrameWeb. Should be documented. 
	 * @throws SaveException */
	public void grantParticipation(Access access) throws SaveException;
	
	public void declineParticipation(Access access) throws SaveException;
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public String revoqueParticipation(Access access);
	
}