package br.ufes.informatica.rationalontology.core.application;

import java.util.List;

import javax.ejb.EJB;
import javax.ejb.Stateless;

import br.ufes.informatica.rationalontology.core.domain.Ontology;
import br.ufes.informatica.rationalontology.core.domain.User;
import br.ufes.informatica.rationalontology.core.persistence.CompetenceQuestionDAO;
import br.ufes.informatica.rationalontology.core.persistence.DataDictionaryDAO;
import br.ufes.informatica.rationalontology.core.persistence.OntologyDAO;
import br.ufes.informatica.rationalontology.core.persistence.SubOntologyDAO;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class OntologyControllerBean implements OntologyController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private OntologyDAO ontologyDAO;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private DataDictionaryDAO dataDictonaryDAO;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private SubOntologyDAO subOntologyDAO;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private CompetenceQuestionDAO competenceQuestionDAO;

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public List findUserOntologies(User user) {
		// FIXME: auto-generated method stub
		return null;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public String generatePDF(Ontology onto) {
		// FIXME: auto-generated method stub
		return null;
	}

}