package br.ufes.informatica.rationalontology.core.application;

import java.io.Serializable;

import javax.ejb.Local;

import br.ufes.informatica.rationalontology.core.domain.Ontology;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface OntologyDevelopmentController extends Serializable {

	/** TODO: generated by FrameWeb. Should be documented. */
	public String saveOntology(Ontology onto);

}