package br.ufes.informatica.rationalontology.core.application;

import java.io.Serializable;
import javax.ejb.Local;

import br.ufes.informatica.rationalontology.core.domain.User;
import br.ufes.informatica.rationalontology.core.exception.RegistrationFailedException;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface RegistrationServiceApp extends Serializable{
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public void getAccess(String email);
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public String getAccess();
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public void save(User user) throws RegistrationFailedException;
	

	
}