package br.ufes.informatica.rationalontology.core.application;

import java.io.Serializable;

import javax.ejb.Local;

import br.ufes.informatica.rationalontology.core.domain.User;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface RegistrationService extends Serializable {

	/** TODO: generated by FrameWeb. Should be documented. */
	public void getAccess(String email);

	/** TODO: generated by FrameWeb. Should be documented. */
	public void register(User user);

}