package br.ufes.informatica.rationalontology.core.application;

import java.io.Serializable;
import javax.ejb.Local;

import br.ufes.inf.nemo.jbutler.ejb.application.CrudService;
import br.ufes.informatica.rationalontology.core.domain.User;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface RegistrationServiceApp extends CrudService<User>{
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public void getAccess(String email);
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public String getAccess();
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public void register(User user);
	
}