package br.ufes.informatica.rationalontology.core.application;

import java.io.Serializable;
import java.util.List;

import javax.ejb.Local;

import br.ufes.informatica.rationalontology.core.domain.Access;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface RequestParticipationApp extends Serializable {
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public List findOntologyByName(String name);
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public String requestParticipation(Access access);
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public List findRequests(String email);
	
}