package br.ufes.informatica.rationalontology.core.application;

import java.io.Serializable;
import java.util.List;
import javax.ejb.Local;

import br.ufes.informatica.rationalontology.core.domain.Access;
import br.ufes.informatica.rationalontology.core.domain.Ontology;
import br.ufes.informatica.rationalontology.core.exception.RegistrationFailedException;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface RequestParticipationApp extends Serializable {
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public List<Ontology> findOntologyByName(String name);
	
	public List<Ontology> findOntologyByNameNotMine(String name);
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public List<Access> getRequests();
	
	public void cancellParticipation(Access access) throws RegistrationFailedException;
	
	public void saveNewParticipation(Access access) throws RegistrationFailedException;
	
	public void checkAuthorization();
	
}