package br.ufes.informatica.rationalontology.core.application;

import javax.ejb.EJB;
import javax.ejb.Stateless;

import br.ufes.informatica.rationalontology.core.domain.SubOntology;
import br.ufes.informatica.rationalontology.core.persistence.SubOntologyDAO;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class SubOntologyDevelopmentAppBean implements SubOntologyDevelopmentApp {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private SubOntologyDAO subOntologyDAO;

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public String saveSubOntology(SubOntology subOnt) {
		// FIXME: auto-generated method stub
		return null;
	}

}