package br.ufes.informatica.rationalontology.core.application;

import java.util.List;

import javax.annotation.security.RolesAllowed;
import javax.ejb.EJB;
import javax.ejb.Stateless;

import br.ufes.informatica.rationalontology.core.domain.Ontology;
import br.ufes.informatica.rationalontology.core.domain.SubOntology;
import br.ufes.informatica.rationalontology.core.persistence.SubOntologyDAO;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
@RolesAllowed("SysAdmin")
public class SubOntologyAppBean implements SubOntologyApp {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private SubOntologyDAO subOntologyDAO;

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public void saveSubOntology(SubOntology subOnt) {
		subOntologyDAO.save(subOnt);
	}

	@Override
	public List<SubOntology> getSubOntologiesByOntology(Ontology ontology) {
		return subOntologyDAO.getSubOntologyByOntology(ontology);
	}

	@Override
	public void checkAuthorization() {
		System.out.println("checkAuthorization");
	}

}