package br.ufes.informatica.rationalontology.core.controller;

import java.util.List;

import javax.ejb.EJB;
import javax.enterprise.inject.*;
import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;
import br.ufes.informatica.rationalontology.core.domain.CompetenceQuestion;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class CompetenceQuestionController extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	
	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private CompetenceQuestionController competenceQuestionController;
	

	
	/** TODO: generated by FrameWeb. Should be documented. */
	private CompetenceQuestion competenceQuestion;
	
	/** TODO: generated by FrameWeb. Should be documented. */
	private List competenceQuestionList;
	

	
	/** TODO: generated by FrameWeb. Should be documented. */
	public String saveCQ() {
		// FIXME: auto-generated method stub
		return null;
	}
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public void findCompetenceQuestion() {
		// FIXME: auto-generated method stub
		return;
	}
	
	
	
	/** Getter for competenceQuestion. */
	public CompetenceQuestion getCompetenceQuestion() {
		return competenceQuestion;
	}

	/** Setter for competenceQuestion. */
	public void setCompetenceQuestion(CompetenceQuestion competenceQuestion) {
		this.competenceQuestion = competenceQuestion;
	}
	
	/** Getter for competenceQuestionList. */
	public List getCompetenceQuestionList() {
		return competenceQuestionList;
	}

	/** Setter for competenceQuestionList. */
	public void setCompetenceQuestionList(List competenceQuestionList) {
		this.competenceQuestionList = competenceQuestionList;
	}
	
}