package br.ufes.informatica.rationalontology.core.controller;

import java.util.List;

import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.enterprise.inject.*;
import javax.inject.Inject;
import javax.inject.Named;

import br.ufes.inf.nemo.jbutler.ejb.application.CrudService;
import br.ufes.inf.nemo.jbutler.ejb.controller.CrudController;
import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;
import br.ufes.informatica.rationalontology.core.application.CompetenceQuestionApp;
import br.ufes.informatica.rationalontology.core.domain.CompetenceQuestion;
import br.ufes.informatica.rationalontology.core.domain.User;

/** TODO: generated by FrameWeb. Should be documented. */
@Named @SessionScoped
public class CompetenceQuestionController extends CrudController<CompetenceQuestion> {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	
	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private CompetenceQuestionApp competenceQuestionApp;
	

	
	/** TODO: generated by FrameWeb. Should be documented. */
	//private CompetenceQuestion competenceQuestion;
	
	/** TODO: generated by FrameWeb. Should be documented. */
	private List competenceQuestionList;
	

	
	/** TODO: generated by FrameWeb. Should be documented. */
	public String saveCQ() {
		// FIXME: auto-generated method stub
		return null;
	}
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public void findCompetenceQuestion() {
		// FIXME: auto-generated method stub
		return;
	}
	/*s
	
	
	// Getter for competenceQuestion.
	public CompetenceQuestion getCompetenceQuestion() {
		return competenceQuestion;
	}

	// Setter for competenceQuestion.
	public void setCompetenceQuestion(CompetenceQuestion competenceQuestion) {
		this.competenceQuestion = competenceQuestion;
	}
	
	// Getter for competenceQuestionList.
	public List getCompetenceQuestionList() {
		return competenceQuestionList;
	}

	// Setter for competenceQuestionList.
	public void setCompetenceQuestionList(List competenceQuestionList) {
		this.competenceQuestionList = competenceQuestionList;
	}
*/
	@Override
	protected CrudService<CompetenceQuestion> getCrudService() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	protected void initFilters() {
		// TODO Auto-generated method stub
		
	}
	
}