package br.ufes.informatica.rationalontology.core.controller;

import java.util.List;

import javax.ejb.EJB;
import javax.enterprise.inject.Model;

import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;
import br.ufes.informatica.rationalontology.core.application.DictionaryController;
import br.ufes.informatica.rationalontology.core.domain.DataDictionary;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class DictionaryContoller extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private DictionaryController dictionaryController;

	/** TODO: generated by FrameWeb. Should be documented. */
	private DataDictionary dictionary;

	/** TODO: generated by FrameWeb. Should be documented. */
	private List dataList;

	/** Getter for dictionary. */
	public DataDictionary getDictionary() {
		return dictionary;
	}

	/** Setter for dictionary. */
	public void setDictionary(DataDictionary dictionary) {
		this.dictionary = dictionary;
	}

	/** Getter for dataList. */
	public List getDataList() {
		return dataList;
	}

	/** Setter for dataList. */
	public void setDataList(List dataList) {
		this.dataList = dataList;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	public String saveDictionary() {
		// FIXME: auto-generated method stub
		return null;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	public List findDataDictionary() {
		// FIXME: auto-generated method stub
		return null;
	}

}