package br.ufes.informatica.rationalontology.core.controller;

import java.util.List;

import javax.ejb.EJB;
import javax.enterprise.inject.*;
import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;
import br.ufes.informatica.rationalontology.core.application.GrantParticipationApp;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class GrantParticipationController extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private GrantParticipationApp grantParticipation;

	/** TODO: generated by FrameWeb. Should be documented. */
	private List requests;

	/** TODO: generated by FrameWeb. Should be documented. */
	public List findRequests() {
		// FIXME: auto-generated method stub
		return null;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	public String grantParticipation() {
		// FIXME: auto-generated method stub
		return null;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	public String revoqueParticipation() {
		// FIXME: auto-generated method stub
		return null;
	}

	/** Getter for requests. */
	public List getRequests() {
		return requests;
	}

	/** Setter for requests. */
	public void setRequests(List requests) {
		this.requests = requests;
	}

}