package br.ufes.informatica.rationalontology.core.controller;

import java.util.List;

import javax.ejb.EJB;
import javax.enterprise.inject.*;
import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;
import br.ufes.informatica.rationalontology.core.application.OntologyDevelopmentController;
import br.ufes.informatica.rationalontology.core.domain.Ontology;
import br.ufes.informatica.rationalontology.core.domain.SubOntology;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class OntologyDevelopmentControler extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private OntologyDevelopmentController ontologyDevelopmentController;

	/** TODO: generated by FrameWeb. Should be documented. */
	private Ontology ontology;

	/** TODO: generated by FrameWeb. Should be documented. */
	private SubOntology subOntology;

	/** TODO: generated by FrameWeb. Should be documented. */
	private List subOntologiesList;

	/** TODO: generated by FrameWeb. Should be documented. */
	public String saveOntology() {
		// FIXME: auto-generated method stub
		return null;
	}

	/** Getter for ontology. */
	public Ontology getOntology() {
		return ontology;
	}

	/** Setter for ontology. */
	public void setOntology(Ontology ontology) {
		this.ontology = ontology;
	}

	/** Getter for subOntology. */
	public SubOntology getSubOntology() {
		return subOntology;
	}

	/** Setter for subOntology. */
	public void setSubOntology(SubOntology subOntology) {
		this.subOntology = subOntology;
	}

	/** Getter for subOntologiesList. */
	public List getSubOntologiesList() {
		return subOntologiesList;
	}

	/** Setter for subOntologiesList. */
	public void setSubOntologiesList(List subOntologiesList) {
		this.subOntologiesList = subOntologiesList;
	}

}