package br.ufes.informatica.rationalontology.core.controller;

import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

import br.ufes.inf.nemo.jbutler.ejb.application.CrudService;
import br.ufes.inf.nemo.jbutler.ejb.controller.CrudController;
import br.ufes.informatica.rationalontology.core.application.RegistrationServiceApp;
import br.ufes.informatica.rationalontology.core.domain.User;

/** TODO: generated by FrameWeb. Should be documented. */
@Named @SessionScoped
public class RegistrationController extends CrudController<User> {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	
	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private RegistrationServiceApp registrationServiceApp;	


	/** TODO: generated by FrameWeb. Should be documented. */
	private String repeatPassword;
	private String email;
	private String password;
	
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public String getAccess() {
		System.out.println("Dados: "+email +"  "+password);
		return registrationServiceApp.getAccess();
	}

	@Override
	protected CrudService<User> getCrudService() {
		// TODO Auto-generated method stub
		return registrationServiceApp;
	}

	@Override
	protected void initFilters() {
		// TODO Auto-generated method stub
		
	}
	
}