package br.ufes.informatica.rationalontology.core.controller;

import java.util.List;

import javax.ejb.EJB;
import javax.enterprise.inject.*;
import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;
import br.ufes.informatica.rationalontology.core.application.RequestParticipation;
import br.ufes.informatica.rationalontology.core.domain.Access;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class RequestParticipationController extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private RequestParticipation requestParticipation;

	/** TODO: generated by FrameWeb. Should be documented. */
	private Access access;

	/** TODO: generated by FrameWeb. Should be documented. */
	private List ontologies;

	/** TODO: generated by FrameWeb. Should be documented. */
	private String requestDescription;

	/** TODO: generated by FrameWeb. Should be documented. */
	private String ontologyName;

	/** TODO: generated by FrameWeb. Should be documented. */
	private List requests;

	/** TODO: generated by FrameWeb. Should be documented. */
	public List findOntologyByName() {
		// FIXME: auto-generated method stub
		return null;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	public String requestParticipation() {
		// FIXME: auto-generated method stub
		return null;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	public List findRequests() {
		// FIXME: auto-generated method stub
		return null;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	private void sendEMail() {
		// FIXME: auto-generated method stub
		return;
	}

	/** Getter for access. */
	public Access getAccess() {
		return access;
	}

	/** Setter for access. */
	public void setAccess(Access access) {
		this.access = access;
	}

	/** Getter for ontologies. */
	public List getOntologies() {
		return ontologies;
	}

	/** Setter for ontologies. */
	public void setOntologies(List ontologies) {
		this.ontologies = ontologies;
	}

	/** Getter for requestDescription. */
	public String getRequestDescription() {
		return requestDescription;
	}

	/** Setter for requestDescription. */
	public void setRequestDescription(String requestDescription) {
		this.requestDescription = requestDescription;
	}

	/** Getter for ontologyName. */
	public String getOntologyName() {
		return ontologyName;
	}

	/** Setter for ontologyName. */
	public void setOntologyName(String ontologyName) {
		this.ontologyName = ontologyName;
	}

	/** Getter for requests. */
	public List getRequests() {
		return requests;
	}

	/** Setter for requests. */
	public void setRequests(List requests) {
		this.requests = requests;
	}

}