package br.ufes.informatica.rationalontology.core.controller;

import javax.ejb.EJB;
import javax.enterprise.inject.*;
import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;
import br.ufes.informatica.rationalontology.core.application.SubOntologyDevelopmentController;
import br.ufes.informatica.rationalontology.core.domain.SubOntology;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class SubOntologyDevelpmentController extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private SubOntologyDevelopmentController subOntologyDevelopmentController;

	/** TODO: generated by FrameWeb. Should be documented. */
	private SubOntology subOntology;

	/** TODO: generated by FrameWeb. Should be documented. */
	public String saveSubOntolgoy() {
		// FIXME: auto-generated method stub
		return null;
	}

	/** Getter for subOntology. */
	public SubOntology getSubOntology() {
		return subOntology;
	}

	/** Setter for subOntology. */
	public void setSubOntology(SubOntology subOntology) {
		this.subOntology = subOntology;
	}

}